# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/lockdead.png'

# Special
background='#000004'
foreground='#F7F8FC'
cursor='#A1ABB6'

# Colors
color0='#000004'
color1='#5D434E'
color2='#4B5D70'
color3='#69859D'
color4='#ABB0BB'
color5='#ACDBE9'
color6='#E8ECF7'
color7='#EBEDF3'
color8='#A4A6AA'
color9='#5D434E'
color10='#4B5D70'
color11='#69859D'
color12='#ABB0BB'
color13='#ACDBE9'
color14='#E8ECF7'
color15='#EBEDF3'

# FZF colors
#export FZF_DEFAULT_OPTS="
#    $FZF_DEFAULT_OPTS
#    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
#    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
#"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
