# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/ign_unsplash34.png'

# Special
background='#000004'
foreground='#F9F9FB'
cursor='#AB9EA5'

# Colors
color0='#000004'
color1='#2E3440'
color2='#5D434E'
color3='#69859D'
color4='#A9ABB5'
color5='#ACDBE9'
color6='#EFEFF4'
color7='#EFEFF1'
color8='#A7A7A9'
color9='#2E3440'
color10='#5D434E'
color11='#69859D'
color12='#A9ABB5'
color13='#ACDBE9'
color14='#EFEFF4'
color15='#EFEFF1'

# FZF colors
#export FZF_DEFAULT_OPTS="
#    $FZF_DEFAULT_OPTS
#    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
#    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
#"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
