# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/ign_unsplash26.png'

# Special
background='#000006'
foreground='#EAE8E1'
cursor='#B3A2A8'

# Colors
color0='#000006'
color1='#384051'
color2='#7C5D6F'
color3='#5E7BA0'
color4='#C38586'
color5='#84BED4'
color6='#C4BDAA'
color7='#D9D6CC'
color8='#98958F'
color9='#384051'
color10='#7C5D6F'
color11='#5E7BA0'
color12='#C38586'
color13='#84BED4'
color14='#C4BDAA'
color15='#D9D6CC'

# FZF colors
#export FZF_DEFAULT_OPTS="
#    $FZF_DEFAULT_OPTS
#    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
#    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
#"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
