$primary_paletteKeyColor = 348382
$secondary_paletteKeyColor = 617c7c
$tertiary_paletteKeyColor = d1b6f1
$neutral_paletteKeyColor = 747877
$neutral_variant_paletteKeyColor = 6f7979
$background = 101414
$onBackground = e0e3e2
$surface = 101414
$surfaceDim = 101414
$surfaceBright = 363a3a
$surfaceContainerLowest = 0b0f0f
$surfaceContainerLow = 181c1c
$surfaceContainer = 1c2020
$surfaceContainerHigh = 272b2a
$surfaceContainerHighest = 323535
$onSurface = e0e3e2
$surfaceVariant = 3f4948
$onSurfaceVariant = bec9c8
$inverseSurface = e0e3e2
$inverseOnSurface = 2d3131
$outline = 889392
$outlineVariant = 3f4948
$shadow = 000000
$scrim = 000000
$surfaceTint = 87d3d2
$primary = 6cb8b7
$onPrimary = 002525
$primaryContainer = 82cecd
$onPrimaryContainer = 005858
$inversePrimary = 0d6969
$secondary = afcccb
$onSecondary = 1a3534
$secondaryContainer = 314b4b
$onSecondaryContainer = 9ebbba
$tertiary = d6bbf7
$onTertiary = 3b2657
$tertiaryContainer = 9f86be
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = a3f0ef
$primaryFixedDim = 87d3d2
$onPrimaryFixed = 002020
$onPrimaryFixedVariant = 00504f
$secondaryFixed = cbe8e7
$secondaryFixedDim = afcccb
$onSecondaryFixed = 03201f
$onSecondaryFixedVariant = 314b4b
$tertiaryFixed = eedcff
$tertiaryFixedDim = d6bbf7
$onTertiaryFixed = 250f40
$onTertiaryFixedVariant = 523d6f
$term0 = 343434
$term1 = 769e00
$term2 = 52e2c4
$term3 = 7dfcd2
$term4 = 75b5b5
$term5 = 7aaee9
$term6 = 82d8cc
$term7 = cddcd4
$term8 = 9aa59f
$term9 = 85b900
$term10 = 3af7d5
$term11 = ccffeb
$term12 = a3c8c4
$term13 = a2c0f7
$term14 = 8aecdc
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 61ceea
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d2faea
$green = 8cf1e2
$teal = 9eeeea
$sky = 93e9eb
$sapphire = 71d7dd
$blue = 58ccdc
$lavender = 86d9ea
$text = e0e3e2
$subtext1 = bec9c8
$subtext0 = 889392
$overlay2 = 76807f
$overlay1 = 646c6c
$overlay0 = 535b5a
$surface2 = 434a49
$surface1 = 333938
$surface0 = 212626
$base = 101414
$mantle = 101414
$crust = 0f1313
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
